import './globals.css'

import { TareaProvider } from '@/context/TareasContext';
import { Nav } from '@/context/Nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// AQUI SE CONTIENE TODAS LAS RUTAS DE LA APLICACION
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <Nav/>

        <TareaProvider>
          {children}
        </TareaProvider>
      
      </body>
    </html>
  )
}
