import './globals.css'

import { TaskProvider } from '@/context/TasksContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// AQUI SE CONTIENE TODAS LAS RUTAS DE LA APLICACION
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          {children}
        </TaskProvider>
      </body>
    </html>
  )
}
